resolver: lts-10.3
packages:
- '.'
- location:
    git: git@github.com:haskus/haskus-binary
    commit: f2a0e634cb2d9f5d5ec47c24e7209f65b674513b
  extra-dep: true
- location:
    git: git@github.com:haskus/haskus-utils
    commit: 041b9421a4e4ff64b9ac0f7ce43ab0d68b879c9a
  extra-dep: true

extra-deps:
- diagrams-1.4
- diagrams-rasterific-1.4

#allow-newer: true

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code -freverse-errors -fhide-source-paths
   # -fobject-code       -- GHCI needs it because of the foreign primops
   # -freduction-depth=0 -- used to allow compilation of some Variants

build:
   haddock-arguments:
      haddock-args:
         - "--optghc=-freduction-depth=0"

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#
# To test with GHC head, uncomment this and add "ghc-stage2" aliased as "ghc" in
# the PATH
#compiler: ghc-8.0.1.20161117
#system-ghc: true
