resolver: lts-9.6
packages:
- '.'
- location:
    git: git@github.com:hsyl20/haskus-binary
    commit: 86c3020532dc0ead052e761bbb97d88ec61a32e6
  extra-dep: true
- location:
    git: git@github.com:haskus/haskus-utils
    commit: 2d7a7daf84389473d55479d511280398b556376a
  extra-dep: true

extra-deps:
- diagrams-1.4

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code -freverse-errors
   # -fobject-code       -- GHCI needs it because of the foreign primops
   # -freduction-depth=0 -- used to allow compilation of some Variants

build:
   haddock-arguments:
      haddock-args:
         - "--optghc=-freduction-depth=0"
         - "--odir=./doc/haddock"

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#
# To test with GHC head, uncomment this and add "ghc-stage2" aliased as "ghc" in
# the PATH
#compiler: ghc-8.0.1.20161117
#system-ghc: true
