resolver: https://raw.githubusercontent.com/haskus/haskus-snapshots/master/haskus-9.yaml
packages:
- '.'

extra-deps:
- diagrams-1.4
- diagrams-rasterific-1.4

#allow-newer: true

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "$locals": -fhide-source-paths
   "haskus-system": -freduction-depth=0 -fobject-code -freverse-errors
   # -fobject-code       -- GHCI needs it because of the foreign primops
   # -freduction-depth=0 -- used to allow compilation of some Variants

build:
   haddock-arguments:
      haddock-args:
         - "--optghc=-freduction-depth=0"

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#
# To test with GHC head, uncomment this and add "ghc-stage2" aliased as "ghc" in
# the PATH
#compiler: ghc-8.0.1.20161117
#system-ghc: true
