resolver: lts-8.18
packages:
- '.'

extra-deps:
- diagrams-1.4
- haskus-binary-0.6.0.0
- haskus-utils-0.7.0.0

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code
   # -fobject-code       -- GHCI needs it because of the foreign primops
   # -freduction-depth=0 -- used to allow compilation of large type-level Syscalls table

build:
   haddock-arguments:
      haddock-args:
         - "--optghc=-freduction-depth=0"
         - "--odir=./doc/haddock"

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
#
# To test with GHC head, uncomment this and add "ghc-stage2" aliased as "ghc" in
# the PATH
#compiler: ghc-8.0.1.20161117
#system-ghc: true
